apply plugin: 'com.android.application'

android {
    compileSdkVersion 35
    namespace 'is.jobboks.app'

    defaultConfig {
        applicationId "is.jobboks.app"
        minSdkVersion 24
        targetSdkVersion 35
        versionCode 1
        versionName "1.0.0"
    }

    signingConfigs {
        release {
            storeFile rootProject.file('android.keystore')
            storePassword 'jobboks123'
            keyAlias 'jobboks'
            keyPassword 'jobboks123'
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
